version: "3.7"
services:
  web-server:
    build:
      dockerfile: php.Dockerfile
      context: .
    restart: always
    volumes:
      - "./:/var/www/html/:z"
    ports:
      - "8080:80"
  mysql-server:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: qwerty
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: mysql-server
      PMA_USER: root
      PMA_PASSWORD: qwerty
    ports:
      - "5000:80"
volumes:
  mysql-data:
